// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjK_GPjkfwg08eLsP0d4pqd1LuMJtUL58',
    appId: '1:549822134327:web:ed5169328f4727128e67b2',
    messagingSenderId: '549822134327',
    projectId: 'anbu-memory',
    authDomain: 'anbu-memory.firebaseapp.com',
    storageBucket: 'anbu-memory.appspot.com',
    measurementId: 'G-MWGPKNVWSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8God2WVW_HunaAW9wwzjCDkBUaupBWQ0',
    appId: '1:549822134327:android:60f3842e77416ba78e67b2',
    messagingSenderId: '549822134327',
    projectId: 'anbu-memory',
    storageBucket: 'anbu-memory.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMnohMEIZo9ArudPPUrmzDjykuD2JPmdo',
    appId: '1:549822134327:ios:acd96d84125e72a78e67b2',
    messagingSenderId: '549822134327',
    projectId: 'anbu-memory',
    storageBucket: 'anbu-memory.appspot.com',
    iosBundleId: 'com.example.anbuMemory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMnohMEIZo9ArudPPUrmzDjykuD2JPmdo',
    appId: '1:549822134327:ios:6da4047ce834bc378e67b2',
    messagingSenderId: '549822134327',
    projectId: 'anbu-memory',
    storageBucket: 'anbu-memory.appspot.com',
    iosBundleId: 'com.example.anbuMemory.RunnerTests',
  );
}
